#!/bin/bash

set -e

cd "$(dirname "$0")/.."

version="$1"

if [ -z "$version" ] || [ ! -d "$version" ]; then
  echo Usage: test/run VERSION
  exit 1
fi

docker build --rm --force-rm -t spraints/playwright-test "$version"

docker run -it --rm \
  -v $(pwd)/test:/testsrc:ro \
  -w /test \
  spraints/playwright-test \
  bash -xec "cp -Rpv /testsrc/* . && npm install --save playwright@$version && node smoke-test.js"
